[package]
name = "rerun-viewer"
version = "0.1.0"
edition = "2021"

[dependencies]
make87 = { version = "0.2.4", features=["zenoh", "rerun"] }
tokio = "1.45.1"
serde_json = "1.0.140"
regex = "1.10"
rerun = "0.25.1"